minesweeper_ncurses: minesweeper_ncurses.c ../da26/keymaps/default/minesweeper.c
	gcc -I../da26/keymaps/default -g -o minesweeper_ncurses minesweeper_ncurses.c ../da26/keymaps/default/minesweeper.c -lncurses

clean:
	rm -f minesweeper_ncurses log.txt
